### PR TITLE
Groups and registrations in account overview

### PR DESCRIPTION
**Pull request by jasperweyne**
This PR adds an overview of all the activities a user account has been registered to, as well as an overview of all the groups that an account has been linked with. This information has been added to the user admin page. To accomplish this, the tabbing functionality in the admin has been extracted to a component. All existing tabs have been refactored to utilize this code.

### CODE REVIEW

**Comment by A-Daneel** [comment]
Looks like a nice addition, I initially thought(hoped?) the list of upcoming activities per person would also be visible for said person. Maybe a different PR.

For this one, I think it might also be nice to have a tab displaying the past activities someone has gone to, and if they attended. thoughts? (could be useful to have an easy display of how active your new members are).

**Comment by jasperweyne** [comment]
This overview shows all registrations, past, present and future. Presence is indicated as well.

**Comment by A-Daneel** [comment]
my bad, only looked at the fixtures that where loaded. Looks great, think this will be very useful!

**Review by A-Daneel — APPROVED** [review]
Removed @mkrugr since this PR was open for a week, and I couldn't approve it without doing so

**Pull request merged**
