### PR TITLE
fix(passwordController): deduplication of code

### PR DESCRIPTION
**Pull request by A-Daneel**
is that even a word? deduplication???

### CODE REVIEW

**Comment by A-Daneel** [comment]
spicy 0% duplication, will try and write the test's for this tomorrow.
Not really sure what's going on with the [Person Entity](https://github.com/jasperweyne/helpless-kiwi/blob/19c803029aa3234f00b72ebad7cb234945223bac/src/Controller/Security/PasswordController.php#L5)... @jasperweyne any suggestions?

**Comment by jasperweyne** [comment]
Hmm, remnant from a refactor, I believe that Person should refer to a App/Entity/Security/LocalAccount

**Comment by A-Daneel** [comment]
That was indeed the issue, changed it since I think it falls under the scope of this refactor branch. agreed?

**Comment by A-Daneel** [comment]
@jasperweyne could you please check why sonarcloud isn't showing anything nor willing to rerun. I assume it's a permission issue and you just have to press the magic button :)

**Comment by A-Daneel** [comment]
### Update
* We reached the needed 85% coverage.
* The lines that aren't covered now are related to a current bug (passing an invalid email throws a 500 error).
* This issue needs to be resolved first, once this is done the testcase shall be added.

**Review by mkrugr — APPROVED** [review]
Clean code, as forced by solarlint. No errors when running the tests and locally testing the accounts.

**Pull request merged**
