### PR TITLE
Social & community

### PR DESCRIPTION
**Pull request by jasperweyne**

### CODE REVIEW

**Review by mkrugr — DISMISSED** [review]
I do no disagree and could not find any spelling errors. So this pull request is fine.

**Comment by A-Daneel** [comment]
I can't find any major logistical or grammatical errors.
With this in mind we can merge it so new members will have guidelines and some structure.
There are some small points where I wasn't completely sure about so read them through and either change or merge depending on if you agree. ^.^


Code of Conduct:
- It seems a bit vague at certain parts. However I don't see how it could be better written out, so it's important that the active members covey the intended meaning to the new members. If that works out we can leave it like this, otherwise we should revisit this.

Contributing:
- line 51 small visual suggestion, shouldn't the master branch be above the develop?
- lastly at line 78 it says "in the example as shown below", but I don't see an example.

**Review by A-Daneel — DISMISSED** [review]
I can't find any major logistical or grammatical errors.
With this in mind we can merge it so new members will have guidelines and some structure.
There are some small points where I wasn't completely sure about so read them through and either change or merge depending on if you agree. ^.^


Code of Conduct:
- It seems a bit vague at certain parts. However I don't see how it could be better written out, so it's important that the active members covey the intended meaning to the new members. If that works out we can leave it like this, otherwise we should revisit this.

Contributing:
- line 51 small visual suggestion, shouldn't the master branch be above the develop?
- lastly at line 78 it says "in the example as shown below", but I don't see an example.

**Comment by jasperweyne** [comment]
@A-Daneel, thanks for your review. I'd like to respond to your notes. First, your note considering the CoC.

>     * It seems a bit vague at certain parts. However I don't see how it could be better written out, so it's important that the active members covey the intended meaning to the new members. If that works out we can leave it like this, otherwise we should revisit this.

I'd agree it may be a bit vague, but I believe that's a good thing for a code of conduct; a certain (but limited) level of broad applicability is valuable for a document that is intended to outline acceptable and unacceptable behavior, since it's usually dependent on context and the persons involved. If we'd like to specify things further, this should be taken into account at that time.

Then regarding the contributing document.

>     * line 51 small visual suggestion, shouldn't the master branch be above the develop?

Since the develop branch is the default branch on opening the repository, I'd say for a new user this branch should be explained first. From a hierarchical, it's a bit odd ofcourse, but I do feel like this accustoms new contributors best.   

>     * lastly at line 78 it says "in the example as shown below", but I don't see an example.

I'll add this shortly, thanks for noting!

**Pull request merged**
