### PR TITLE
Security refactor

### PR DESCRIPTION
**Pull request by mkrugr**
This pull-request fixes the 'optional' oidc-client class, some broken yaml configs. In addition it provides our third authentication method. This time by means of access tokens, which is the correct way of implementing this. 

Lastly it updates a few packages, including a lot of symfony bundles. Symfony 5.4 is now enforced across all bundles.

### CODE REVIEW

**Comment by mkrugr** [comment]
I will fix these tests later

**Comment by jasperweyne** [comment]
I see that currently, the OptionalOidcClient has been removed, but no alternative solution has been implemented. How are you planning on supporting setups without OIDC enabled? eg.: 
Screenshot 2022-11-05 at 15-27-28 Invalid well known url (http ___ well-known_openid-configuration) for OIDC (500 Internal Server Error)

**Review by jasperweyne — COMMENTED** [review]
Given the fact that commits were pushed since my initial comment, I'll assume a new review is desired. In the future, please send a message indicating so!

Tbh, this PR feels like a mess. All packages have been updated, without any clear indication as to why this was necessary. The package version constraints in composer.json have been updated to 5.4, while this was already enforced by the "extra.symfony.require" field in that same file. In a number of files, defaults were uncommented or spaces or new lines were added or removed without a clear reason why. The `loadAccessTokenUser` method has been added to the LocalUserProvider, whose implementation is an exact copy of the `loadOidcUser` method directly above, and the new method isn't called anywhere.

I see three substantive changes:
- the well_known_url in drenso_oidc.yaml has been fixed
- the AccessTokenAuthenticator has been added for API related purposes
- OidcClientFactory and the MockOidcClient have been introduced to replace the OptionalOidcClient

Those are fine improvements and I actually like those changes quite a bit. However, I feel like those changes are not necessarily interrelated which each other, let alone with all the redundant changes all over the codebase. I'm strongly inclined to decline this PR altogether for now and to request that you split it up into smaller PRs, without the needless modifications.

If I made any wrong assumptions or conclusions on this matter and this PR needs to be combined with all three improvements, please let me know and we can discuss this PR further in depth. If you agree that this PR can be split up however, please close this PR and open up the three new PRs.

**Comment by mkrugr** [comment]
I agree with Jasper that this pull request should be split in multiple ones.

**Pull request closed without merging**
